version: "3"

services:
  db_challenge_backend:
    image: mysql:latest
    container_name: db_challenge_backend
    ports:
      - 3306:3306
    command:
      - "mysqld"
      - "--innodb_buffer_pool_size=512M"
      - "--ft-min_word-len=1"
      - "--ft-stopword-file=''"
    networks:
      - net_back
    network_mode: bridge
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=challenges
      - MYSQL_USER=usuario_teste
      - MYSQL_PASSWORD=teste123456
      - MYSQL_ROOT_PASSWORD=teste123456
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

#  postgres:
#    image: postgres:latest
#    container_name: db_challenge_postgres
#    ports:
#      - 5432:5432
#    expose:
#      - 5432
#    networks:
#      - net_back
#    network_mode: bridge
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    restart: always
#    environment:
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=challenges
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 1024M
          
  microservico:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - JAR_FILE=challenge-backend-api.jar
    image: testeluismatos/challenge-backend-api:0.0.1
    container_name: microservico
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_challenge_backend:3306/challenges
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080
    networks:
      - net_back
    depends_on:
      - db_challenge_backend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
          
networks:
  net_back:
    driver: bridge
  
volumes:
  mysql: 
  postgres-data:
  