version: "3"

services:
  db_challenge_backend:
    image: mysql:5.7
    container_name: db_challenge_backend
    ports:
      - 3306:3306
    networks:
      - net_back
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=challenges
      - MYSQL_USER=usuario_teste
      - MYSQL_PASSWORD=teste123456
      - MYSQL_ROOT_PASSWORD=teste123456
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
          
  microservico:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - JAR_FILE=challenge-backend-api.jar
    image: testeluismatos/challenge-backend-api:0.0.1
    container_name: microservico
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_challenge_backend:3306/challenges?autoReconnect=true&useSSL=false
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080
    networks:
      - net_back
    depends_on:
      - db_challenge_backend
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
          
networks:
  net_back:
  
volumes:
  mysql: null
  